/**
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2022 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

#ifndef _REG_MAP_H_
#define _REG_MAP_H_

#define __ctrl_reg_base 0x6800

#define ISPU_GLB_CALL_EN  (__ctrl_reg_base + 0x00)
#define ISPU_CONFIG       (__ctrl_reg_base + 0x02)
#define ISPU_STATUS       (__ctrl_reg_base + 0x04)
#define ISPU_IF2S_FLAG    (__ctrl_reg_base + 0x0C)
#define ISPU_S2IF_FLAG    (__ctrl_reg_base + 0x0E)
#define ISPU_DOUT_00      (__ctrl_reg_base + 0x10)
#define ISPU_DOUT_00_B    (__ctrl_reg_base + 0x11)
#define ISPU_DOUT_01      (__ctrl_reg_base + 0x12)
#define ISPU_DOUT_01_B    (__ctrl_reg_base + 0x13)
#define ISPU_DOUT_02      (__ctrl_reg_base + 0x14)
#define ISPU_DOUT_02_B    (__ctrl_reg_base + 0x15)
#define ISPU_DOUT_03      (__ctrl_reg_base + 0x16)
#define ISPU_DOUT_03_B    (__ctrl_reg_base + 0x17)
#define ISPU_DOUT_04      (__ctrl_reg_base + 0x18)
#define ISPU_DOUT_04_B    (__ctrl_reg_base + 0x19)
#define ISPU_DOUT_05      (__ctrl_reg_base + 0x1A)
#define ISPU_DOUT_05_B    (__ctrl_reg_base + 0x1B)
#define ISPU_DOUT_06      (__ctrl_reg_base + 0x1C)
#define ISPU_DOUT_06_B    (__ctrl_reg_base + 0x1D)
#define ISPU_DOUT_07      (__ctrl_reg_base + 0x1E)
#define ISPU_DOUT_07_B    (__ctrl_reg_base + 0x1F)
#define ISPU_DOUT_08      (__ctrl_reg_base + 0x20)
#define ISPU_DOUT_08_B    (__ctrl_reg_base + 0x21)
#define ISPU_DOUT_09      (__ctrl_reg_base + 0x22)
#define ISPU_DOUT_09_B    (__ctrl_reg_base + 0x23)
#define ISPU_DOUT_10      (__ctrl_reg_base + 0x24)
#define ISPU_DOUT_10_B    (__ctrl_reg_base + 0x25)
#define ISPU_DOUT_11      (__ctrl_reg_base + 0x26)
#define ISPU_DOUT_11_B    (__ctrl_reg_base + 0x27)
#define ISPU_DOUT_12      (__ctrl_reg_base + 0x28)
#define ISPU_DOUT_12_B    (__ctrl_reg_base + 0x29)
#define ISPU_DOUT_13      (__ctrl_reg_base + 0x2A)
#define ISPU_DOUT_13_B    (__ctrl_reg_base + 0x2B)
#define ISPU_DOUT_14      (__ctrl_reg_base + 0x2C)
#define ISPU_DOUT_14_B    (__ctrl_reg_base + 0x2D)
#define ISPU_DOUT_15      (__ctrl_reg_base + 0x2E)
#define ISPU_DOUT_15_B    (__ctrl_reg_base + 0x2F)
#define ISPU_DOUT_16      (__ctrl_reg_base + 0x30)
#define ISPU_DOUT_16_B    (__ctrl_reg_base + 0x31)
#define ISPU_DOUT_17      (__ctrl_reg_base + 0x32)
#define ISPU_DOUT_17_B    (__ctrl_reg_base + 0x33)
#define ISPU_DOUT_18      (__ctrl_reg_base + 0x34)
#define ISPU_DOUT_18_B    (__ctrl_reg_base + 0x35)
#define ISPU_DOUT_19      (__ctrl_reg_base + 0x36)
#define ISPU_DOUT_19_B    (__ctrl_reg_base + 0x37)
#define ISPU_DOUT_20      (__ctrl_reg_base + 0x38)
#define ISPU_DOUT_20_B    (__ctrl_reg_base + 0x39)
#define ISPU_DOUT_21      (__ctrl_reg_base + 0x3A)
#define ISPU_DOUT_21_B    (__ctrl_reg_base + 0x3B)
#define ISPU_DOUT_22      (__ctrl_reg_base + 0x3C)
#define ISPU_DOUT_22_B    (__ctrl_reg_base + 0x3D)
#define ISPU_DOUT_23      (__ctrl_reg_base + 0x3E)
#define ISPU_DOUT_23_B    (__ctrl_reg_base + 0x3F)
#define ISPU_DOUT_24      (__ctrl_reg_base + 0x40)
#define ISPU_DOUT_24_B    (__ctrl_reg_base + 0x41)
#define ISPU_DOUT_25      (__ctrl_reg_base + 0x42)
#define ISPU_DOUT_25_B    (__ctrl_reg_base + 0x43)
#define ISPU_DOUT_26      (__ctrl_reg_base + 0x44)
#define ISPU_DOUT_26_B    (__ctrl_reg_base + 0x45)
#define ISPU_DOUT_27      (__ctrl_reg_base + 0x46)
#define ISPU_DOUT_27_B    (__ctrl_reg_base + 0x47)
#define ISPU_DOUT_28      (__ctrl_reg_base + 0x48)
#define ISPU_DOUT_28_B    (__ctrl_reg_base + 0x49)
#define ISPU_DOUT_29      (__ctrl_reg_base + 0x4A)
#define ISPU_DOUT_29_B    (__ctrl_reg_base + 0x4B)
#define ISPU_DOUT_30      (__ctrl_reg_base + 0x4C)
#define ISPU_DOUT_30_B    (__ctrl_reg_base + 0x4D)
#define ISPU_DOUT_31      (__ctrl_reg_base + 0x4E)
#define ISPU_DOUT_31_B    (__ctrl_reg_base + 0x4F)
#define ISPU_INT1_CTRL    (__ctrl_reg_base + 0x50)
#define ISPU_INT1_CTRL_B  (__ctrl_reg_base + 0x51)
#define ISPU_INT1_CTRL_C  (__ctrl_reg_base + 0x52)
#define ISPU_INT1_CTRL_D  (__ctrl_reg_base + 0x53)
#define ISPU_INT2_CTRL    (__ctrl_reg_base + 0x54)
#define ISPU_INT2_CTRL_B  (__ctrl_reg_base + 0x55)
#define ISPU_INT2_CTRL_C  (__ctrl_reg_base + 0x56)
#define ISPU_INT2_CTRL_D  (__ctrl_reg_base + 0x57)
#define ISPU_INT_STATUS   (__ctrl_reg_base + 0x58)
#define ISPU_INT_STATUS_B (__ctrl_reg_base + 0x59)
#define ISPU_INT_STATUS_C (__ctrl_reg_base + 0x5A)
#define ISPU_INT_STATUS_D (__ctrl_reg_base + 0x5B)
#define ISPU_INT_PIN      (__ctrl_reg_base + 0x5C)
#define ISPU_ALGO         (__ctrl_reg_base + 0x70)
#define ISPU_ALGO_B       (__ctrl_reg_base + 0x71)
#define ISPU_ALGO_C       (__ctrl_reg_base + 0x72)
#define ISPU_ALGO_D       (__ctrl_reg_base + 0x73)
#define ISPU_ARAW_X       (__ctrl_reg_base + 0x80)
#define ISPU_ARAW_X_B     (__ctrl_reg_base + 0x81)
#define ISPU_ARAW_X_C     (__ctrl_reg_base + 0x82)
#define ISPU_ARAW_X_D     (__ctrl_reg_base + 0x83)
#define ISPU_ARAW_Y       (__ctrl_reg_base + 0x84)
#define ISPU_ARAW_Y_B     (__ctrl_reg_base + 0x85)
#define ISPU_ARAW_Y_C     (__ctrl_reg_base + 0x86)
#define ISPU_ARAW_Y_D     (__ctrl_reg_base + 0x87)
#define ISPU_ARAW_Z       (__ctrl_reg_base + 0x88)
#define ISPU_ARAW_Z_B     (__ctrl_reg_base + 0x89)
#define ISPU_ARAW_Z_C     (__ctrl_reg_base + 0x8A)
#define ISPU_ARAW_Z_D     (__ctrl_reg_base + 0x8B)
#define ISPU_GRAW_X       (__ctrl_reg_base + 0x8C)
#define ISPU_GRAW_X_B     (__ctrl_reg_base + 0x8D)
#define ISPU_GRAW_X_C     (__ctrl_reg_base + 0x8E)
#define ISPU_GRAW_X_D     (__ctrl_reg_base + 0x8F)
#define ISPU_GRAW_Y       (__ctrl_reg_base + 0x90)
#define ISPU_GRAW_Y_B     (__ctrl_reg_base + 0x91)
#define ISPU_GRAW_Y_C     (__ctrl_reg_base + 0x92)
#define ISPU_GRAW_Y_D     (__ctrl_reg_base + 0x93)
#define ISPU_GRAW_Z       (__ctrl_reg_base + 0x94)
#define ISPU_GRAW_Z_B     (__ctrl_reg_base + 0x95)
#define ISPU_GRAW_Z_C     (__ctrl_reg_base + 0x96)
#define ISPU_GRAW_Z_D     (__ctrl_reg_base + 0x97)
#define ISPU_ERAW_0       (__ctrl_reg_base + 0x98)
#define ISPU_ERAW_0_B     (__ctrl_reg_base + 0x99)
#define ISPU_ERAW_0_C     (__ctrl_reg_base + 0x9A)
#define ISPU_ERAW_0_D     (__ctrl_reg_base + 0x9B)
#define ISPU_ERAW_1       (__ctrl_reg_base + 0x9C)
#define ISPU_ERAW_1_B     (__ctrl_reg_base + 0x9D)
#define ISPU_ERAW_1_C     (__ctrl_reg_base + 0x9E)
#define ISPU_ERAW_1_D     (__ctrl_reg_base + 0x9F)
#define ISPU_ERAW_2       (__ctrl_reg_base + 0xA0)
#define ISPU_ERAW_2_B     (__ctrl_reg_base + 0xA1)
#define ISPU_ERAW_2_C     (__ctrl_reg_base + 0xA2)
#define ISPU_ERAW_2_D     (__ctrl_reg_base + 0xA3)
#define ISPU_TEMP         (__ctrl_reg_base + 0xA4)
#define ISPU_TEMP_B       (__ctrl_reg_base + 0xA5)
#define ISPU_TEMP_C       (__ctrl_reg_base + 0xA6)
#define ISPU_TEMP_D       (__ctrl_reg_base + 0xA7)
#define ISPU_CALL_EN      (__ctrl_reg_base + 0xB8)
#define ISPU_CALL_EN_B    (__ctrl_reg_base + 0xB9)
#define ISPU_CALL_EN_C    (__ctrl_reg_base + 0xBA)
#define ISPU_CALL_EN_D    (__ctrl_reg_base + 0xBB)

#define __ctrl_reg_ext 0x6900

#define TIMESTAMP0        (__ctrl_reg_ext + 0x40)
#define TIMESTAMP2        (__ctrl_reg_ext + 0x42)
#define ISPU_DTIME_0      (__ctrl_reg_ext + 0x48)
#define ISPU_DTIME_1      (__ctrl_reg_ext + 0x4A)
#define ISPU_DUMMY_CFG_1  (__ctrl_reg_ext + 0x74)
#define ISPU_DUMMY_CFG_2  (__ctrl_reg_ext + 0x76)
#define ISPU_DUMMY_CFG_3  (__ctrl_reg_ext + 0x78)
#define ISPU_DUMMY_CFG_4  (__ctrl_reg_ext + 0x7A)

#endif

